name: PHP Composer (self-hosted)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on:
    - self-hosted
#    - ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup database
      run: |
        bin/console doctrine:database:drop --force
        bin/console doctrine:database:create
        bin/console doctrine:migrations:migrate --no-interaction
        bin/console doctrine:fixtures:load --purge-with-truncate --no-interaction

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

  unit-tests:
    needs: build
    runs-on:
      - self-hosted

    steps:

      - name: Run test suite
        run: composer run-script test

  integration-tests:
    needs: build
    runs-on:
      - self-hosted

    steps:

      - name: Run test suite
        run: composer run-script test

  integration-tests-report:
    needs: integration-tests
    runs-on:
      - self-hosted

    steps:

      - name: Run test suite
        run: composer run-script test

  deploy:
    needs:
      - unit-tests
      - integration-tests
    runs-on:
      - self-hosted
    environment:
      name: production
      url: https://test-ci.malefici.com
    steps:
#      - name: Install rsync
#        run: |
#          apt-get install rsync
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ vars.HOST_PRODUCTION_IP }} >> ~/.ssh/known_hosts
      - name: copy builds to server
        run: |
          rsync -rt --exclude ./var/* ./* ${{ secrets.SSH_USERNAME }}@${{ vars.HOST_PRODUCTION_IP }}:~
#          rsync -vrm ./* ${{ secrets.SSH_USERNAME }}@${{ vars.HOST_PRODUCTION_IP }}:~
      - name: Restart php-fpm
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ vars.HOST_PRODUCTION_IP }} "bin/console cache:clear --env=prod; bin/console cache:warmup --env=prod; doctrine:migrations:migrate --no-interaction; sudo systemctl restart php8.2-fpm"
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Deploy is done
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}